/**
 * The open patron tiers on /patrons, from Zeffy's public donor list - the
 * same one the donation form shows behind "View all". Donors are grouped
 * by the memory-themed tiers, each rounded down to the nearest point:
 * 25K is $25,088, 8K is $8,192, 2K is $2,048, 256B is $256, 16B is $16. A donor giving
 * several times counts once with their donations summed; below $16, and
 * donations made anonymously, stay off the list. The generated sections
 * live between the zeffy-patrons markers in pages.json, so a run replaces
 * exactly what the previous run wrote and touches nothing hand-written.
 */

const FORM_ID = '62c3f62f-2b29-4cc2-9336-81c6a6afb259'
const API = 'https://api.zeffy.com/_new/trpc/form_getLatestDonations'

export const TIERS = [
  { id: 'patrons-25k', name: '25K', cents: 2_508_800 },
  { id: 'patrons-8k', name: '8K', cents: 819_200 },
  { id: 'patrons-2k', name: '2K', cents: 204_800 },
  { id: 'patrons-256b', name: '256B', cents: 25_600 },
  { id: 'patrons-16b', name: '16B', cents: 1_600 },
]

/** Patrons who gave outside Zeffy, counted in at their pledged point. */
export const OFF_PLATFORM = [
  { name: 'American Cloud', cents: 2_508_800 },
  { name: 'Zeno', cents: 819_200 },
]

export const START_MARK =
  '<!-- zeffy-patrons:start - generated by scripts/lib/zeffy-patrons.mjs, do not edit by hand -->'
export const END_MARK = '<!-- zeffy-patrons:end -->'

/** Every donation on the form, oldest last, paged through the public API. */
export async function fetchDonations(fetcher = fetch) {
  const donations = []
  let cursor = 0
  for (let page = 0; page < 100; page++) {
    const input = encodeURIComponent(
      JSON.stringify({
        formId: FORM_ID,
        limit: 100,
        cursor,
        direction: 'forward',
      }),
    )
    const res = await fetcher(`${API}?input=${input}`, {
      headers: { origin: 'https://www.zeffy.com' },
    })
    if (!res.ok) throw new Error(`zeffy donors → ${res.status}`)
    const data = (await res.json())?.result?.data
    if (!data?.items) throw new Error('zeffy donors → unexpected shape')
    donations.push(...data.items)
    if (data.nextCursor == null) break
    cursor = data.nextCursor
  }
  return donations
}

const escape = (s) => s.replace(/[&<>"']/g, (c) => `&#${c.charCodeAt(0)};`)

const dollars = (cents) => `$${(cents / 100).toLocaleString('en-US')}`

/** Donors per tier: totals per name, rounded down to the nearest point. */
export function tierMembers(donations, extras = OFF_PLATFORM) {
  const totals = new Map()
  for (const { fullName, amount } of donations) {
    // Zeffy joins first and last name, spelling an empty half as "null".
    const name = fullName
      ?.split(/\s+/)
      .filter((part) => part && part !== 'null')
      .join(' ')
    if (!name || !(amount > 0)) continue
    totals.set(name, (totals.get(name) ?? 0) + amount)
  }
  for (const { name, cents } of extras)
    totals.set(name, (totals.get(name) ?? 0) + cents)
  const members = new Map(TIERS.map((tier) => [tier.id, []]))
  for (const [name, total] of totals) {
    const tier = TIERS.find((t) => total >= t.cents)
    if (tier) members.get(tier.id).push({ name, total })
  }
  for (const list of members.values())
    list.sort((a, b) => b.total - a.total || a.name.localeCompare(b.name))
  return members
}

/** The tier blocks as ported-page HTML, wrapped in the markers. They sit
 * inside the All Patrons section, so no section borders of their own. */
export function tierSections(donations) {
  const members = tierMembers(donations)
  const sections = TIERS.map((tier) => {
    const names = members
      .get(tier.id)
      .map((m) => `            <li>${escape(m.name)}</li>`)
      .join('\n')
    return `          <h3 class="patrons__tier" id="${tier.id}">${tier.name}</h3>
          <p class="team__description">Each contributing ${dollars(tier.cents)} or more.</p>
          <ul class="patrons__supporters" aria-label="${tier.name} patrons, largest contributions first">
${names}
          </ul>`
  })
  return `${START_MARK}\n${sections.join('\n\n')}\n          ${END_MARK}`
}

/** The page HTML with the generated span replaced; null when unmarked. */
export function replaceSections(html, generated) {
  const start = html.indexOf(START_MARK)
  const end = html.indexOf(END_MARK)
  if (start < 0 || end < 0) return null
  return html.slice(0, start) + generated + html.slice(end + END_MARK.length)
}
